specfile_path: zezere.spec
synced_files:
  - zezere.spec
  - .packit.yaml
upstream_package_name: zezere
downstream_package_name: zezere
jobs:
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    metadata:
      dist-git-branch: fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
