name: Run CI tests
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install system dependencies
      run: sudo apt-get install gcc python-dev libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install analysis tools
      run: |
        pip install mypy django-stubs flake8 coverage diff-cover
    - name: Check typing
      run: |
        mypy zezere
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run tests
      env:
        SECRET_KEY: citest
      run: |
        python -Werror -m coverage run --append manage.py test
    - name: Test migrations
      env:
        SECRET_KEY: citest
      run: |
        python -m coverage run --append manage.py migrate
    - name: Report on test coverage
      run: |
        coverage report
    - name: Ensure test coverage
      run: |
        coverage xml
        diff-cover coverage.xml --fail-under 100
