name: Build and push docker images
on:
  push:
    branches:
    - master
  schedule:
  # Do a nightly build/push, so that any vulns in deps don't linger
  - cron:  '0 0 * * *'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt-get update
      run: sudo apt-get update
    - name: Install system dependencies
      run: sudo apt-get install libdevmapper-dev
    - name: Install s2i
      run: |
        go get github.com/openshift/source-to-image/cmd/s2i
    - name: s2i build
      run: |
        $HOME/go/bin/s2i build . registry.access.redhat.com/ubi8/python-36 zezere:latest
    - name: Docker Login to GitHub packages
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    #- name: Docker push latest to GitHub Packages
    #  run: |
    #    docker tag zezere:latest docker.pkg.github.com/fedora-iot/zezere/zezere:latest
    #    docker push docker.pkg.github.com/fedora-iot/zezere/zezere:latest
    - name: Docker Login to Quay.io
      uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}
    - name: Docker push latest to Quay.io
      run: |
        docker tag zezere:latest quay.io/fedora-iot/zezere:latest
        docker push quay.io/fedora-iot/zezere:latest
