name: Build and push docker images
on:
  push:
    branches:
    - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install s2i
      run: |
        go get github.com/openshift/source-to-image/cmd/s2i
    - name: s2i build
      run: |
        $HOME/go/bin/s2i build . registry.access.redhat.com/ubi8/python-36 docker.pkg.github.com/fedora-iot/zezere/zezere:latest
    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker push latest
      run: |
        docker push docker.pkg.github.com/fedora-iot/zezere/zezere:latest
